name: Generate Directory Listings

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Run directory listing generator
      run: |
        find . -type d | while read dir; do
          cd "$dir"
          php /path/to/directory-listing.php
          cd - 
        done

    - name: Commit and push changes
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add .
        git commit -m "Update directory listings"
        git push
