name: Generate Directory Listings

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Download the directory listing script
      - name: Download Directory Listing Script
        run: wget https://raw.githubusercontent.com/caendesilva/php-directory-listing/master/directory-listing.php -O directory-listing.php

      # Run the directory listing script
      - name: Run Directory Listing Script
        run: php directory-listing.php

      # Configure git user for committing changes
      - name: Configure Git
        run: |
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m 'Add directory listings'
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
