name: directory-listing
on:
  push:
    branches:
      - master  # Adjust if your default branch is named differently

jobs:
  generate-directory-listings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: master  # Adjust if necessary

      - name: List all directories
        id: list-dirs
        run: |
          dirs=$(find . -type d -not -path './.git*' -not -path './node_modules*')
          echo "Directories found:"
          echo "$dirs"
          echo "::set-output name=dirs::$dirs"

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: ${{ steps.list-dirs.outputs.dirs }}

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: |
            $(echo ${{ steps.list-dirs.outputs.dirs }} | sed 's/^\.\///g')  # Remove leading './'

  deploy:
    needs: generate-directory-listings
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
