name: directory-listing
on:
  push:
    branches:
      - master  # Adjust if your default branch is named differently

jobs:
  generate-directory-listings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: master  # Adjust if necessary

      - name: Generate Directory Listings for notion-pages
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: notion-pages  # Directory to generate index

      - name: Generate Directory Listings for assets
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: assets  # Subdirectory to generate index

      - name: Generate Directory Listings for thumbnails
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: thumbnails  # Another subdirectory to generate index

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: |
            notion-pages
            assets
            thumbnails  # Upload all directories with generated index files

  deploy:
    needs: generate-directory-listings
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
