name: directory-listing
on:
  push:
    branches:
      - master  # Adjust if your default branch is named differently

jobs:
  generate-directory-listings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: master  # Adjust if necessary

      # Find all directories except .git and node_modules
      - name: List all directories
        id: list-dirs
        run: |
          dirs=$(find . -type d -not -path './.git*' -not -path './node_modules*')
          echo "Directories found:"
          echo "$dirs"
          # Save the directories into a multi-line string
          echo "$dirs" > dirs.txt

      # Process directories one-by-one to generate index pages
      - name: Generate Directory Listings
        run: |
          while IFS= read -r dir; do
            echo "Generating index for $dir"
            # Generate directory listings for each found directory
            jayanta525/github-pages-directory-listing@v4.0.0 FOLDER=$dir
          done < dirs.txt

      # Prepare cleaned paths for artifact upload
      - name: Prepare directory paths for upload
        id: prepare-paths
        run: |
          cleaned_dirs=$(cat dirs.txt | sed 's/^\.\///g')  # Remove leading './'
          echo "Cleaned directories:"
          echo "$cleaned_dirs"
          # Save the cleaned directories into a file for upload
          echo "$cleaned_dirs" > cleaned_dirs.txt

      # Upload the directories as artifacts
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: |
            $(cat cleaned_dirs.txt)

  deploy:
    needs: generate-directory-listings
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
